### ISSUE TITLE
Feature: add ability to run slideshow on auxiliary monitor

### ISSUE THREAD

**Issue by psig** [guywinterbotham/ImproTron#8]
Would like ability to show any combo of display options:
Main: Slideshow, Aux: Static Image/Text
Main: Static Image/Text, Aux: Slideshow
Main & Aux: (Same or Different) Static Image/Text
Main & Aux: (Same or Different) Slideshow

(Two different slideshows option might be a stretch & not worth the effort)

Reasoning: During pre-show and halftime, would be nice to have slideshow running on aux monitor pitching classes/camps/upcoming shows.

**Comment by guywinterbotham** [comment]
Let me break this down to see what's left:
Main: Slideshow, Aux: Static Image/Text - Can do this now. There isn't a convenient way to quickly send Hot Buttons to the Aux. The #3 duplicate feature will force that. I'm also going to add a Right Button Click to do that via the Hot Buttons. 
Main: Static Image/Text, Aux: Slideshow: This would be new. Although given the idea we would want a advertiser to see their promo on the big screen I'm not sure the priority. I'll bow to the collective. I do get your point on having it there as people walk past. But they may not stop.
Main & Aux: (Same or Different) Static Image/Text. It can already push images and two sources of text to one or both.
Main & Aux: (Same or Different) Slideshow: We talked about this. We don't have a pipeline of marketing content that would support two displays. The #3 will enable forcing the promo to both monitors.

**Comment by guywinterbotham** [comment]
Closing for this release to see if the combo of additions amount to the whole. If not then we can open a specific issue for what needs to change.
